(provide 'mycfg)

(require 'fontcfg)
(require 'common-cfg)
(require 'latex-cfg)
;;(require 'mu4e-cfg)
(require 'typescript-cfg)
(require 'orgmode-cfg)
(require 'vue-cfg)
(require 'emms-cfg)
(require 'emms-bilibili-cfg)
